config/routes.rb
Cc::Application.routes.draw do
  resources :repentances

  resources :charities

  resources :judgements

  resources :sins

  resources :members

end

app/models/judgement.rb
class Judgement < ActiveRecord::Base
  belongs_to :member
  belongs_to :sin
  attr_accessible :judgement, :timestamp
end

app/controllers/judgements_controller.rb
class JudgementsController < ApplicationController
  # GET /judgements
  # GET /judgements.json
  def index
    @judgements = Judgement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @judgements }
    end
  end

  # GET /judgements/1
  # GET /judgements/1.json
  def show
    @judgement = Judgement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @judgement }
    end
  end

  # GET /judgements/new
  # GET /judgements/new.json
  def new
    @judgement = Judgement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @judgement }
    end
  end

  # GET /judgements/1/edit
  def edit
    @judgement = Judgement.find(params[:id])
  end

  # POST /judgements
  # POST /judgements.json
  def create
    @judgement = Judgement.new(params[:judgement])

    respond_to do |format|
      if @judgement.save
        format.html { redirect_to @judgement, notice: 'Judgement was successfully created.' }
        format.json { render json: @judgement, status: :created, location: @judgement }
      else
        format.html { render action: "new" }
        format.json { render json: @judgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /judgements/1
  # PUT /judgements/1.json
  def update
    @judgement = Judgement.find(params[:id])

    respond_to do |format|
      if @judgement.update_attributes(params[:judgement])
        format.html { redirect_to @judgement, notice: 'Judgement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @judgement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /judgements/1
  # DELETE /judgements/1.json
  def destroy
    @judgement = Judgement.find(params[:id])
    @judgement.destroy

    respond_to do |format|
      format.html { redirect_to judgements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/judgements_helper.rb
module JudgementsHelper
end

app/views/judgements/_form.html.erb
<%= form_for(@judgement) do |f| %>
  <% if @judgement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@judgement.errors.count, "error") %> prohibited this judgement from being saved:</h2>

      <ul>
      <% @judgement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :sin_id %><br />
    <%= f.text_field :sin_id %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :judgement %><br />
    <%= f.text_area :judgement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/judgements/edit.html.erb
<h1>Editing judgement</h1>

<%= render 'form' %>

<%= link_to 'Show', @judgement %> |
<%= link_to 'Back', judgements_path %>

app/views/judgements/index.html.erb
<h1>Listing judgements</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Sin</th>
    <th>Timestamp</th>
    <th>Judgement</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @judgements.each do |judgement| %>
  <tr>
    <td><%= judgement.member_id %></td>
    <td><%= judgement.sin_id %></td>
    <td><%= judgement.timestamp %></td>
    <td><%= judgement.judgement %></td>
    <td><%= link_to 'Show', judgement %></td>
    <td><%= link_to 'Edit', edit_judgement_path(judgement) %></td>
    <td><%= link_to 'Destroy', judgement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Judgement', new_judgement_path %>

app/views/judgements/new.html.erb
<h1>New judgement</h1>

<%= render 'form' %>

<%= link_to 'Back', judgements_path %>

app/views/judgements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @judgement.member_id %>
</p>

<p>
  <b>Sin:</b>
  <%= @judgement.sin_id %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @judgement.timestamp %>
</p>

<p>
  <b>Judgement:</b>
  <%= @judgement.judgement %>
</p>


<%= link_to 'Edit', edit_judgement_path(@judgement) %> |
<%= link_to 'Back', judgements_path %>