config/routes.rb
Cc::Application.routes.draw do
  resources :repentances

  resources :charities

  resources :judgements

  resources :sins

  resources :members

end

app/models/sin.rb
class Sin < ActiveRecord::Base
  belongs_to :member
  has_many :judgements
  has_many :repentances
  
  attr_accessible :sin, :sin_city, :sin_country, :sin_date, :sin_state, :sin_street_name, :sin_street_number, :sin_time, :sin_zipcode, :title
end

app/controllers/sins_controller.rb
class SinsController < ApplicationController
  # GET /sins
  # GET /sins.json
  def index
    @sins = Sin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sins }
    end
  end

  # GET /sins/1
  # GET /sins/1.json
  def show
    @sin = Sin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sin }
    end
  end

  # GET /sins/new
  # GET /sins/new.json
  def new
    @sin = Sin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sin }
    end
  end

  # GET /sins/1/edit
  def edit
    @sin = Sin.find(params[:id])
  end

  # POST /sins
  # POST /sins.json
  def create
    @sin = Sin.new(params[:sin])

    respond_to do |format|
      if @sin.save
        format.html { redirect_to @sin, notice: 'Sin was successfully created.' }
        format.json { render json: @sin, status: :created, location: @sin }
      else
        format.html { render action: "new" }
        format.json { render json: @sin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sins/1
  # PUT /sins/1.json
  def update
    @sin = Sin.find(params[:id])

    respond_to do |format|
      if @sin.update_attributes(params[:sin])
        format.html { redirect_to @sin, notice: 'Sin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sins/1
  # DELETE /sins/1.json
  def destroy
    @sin = Sin.find(params[:id])
    @sin.destroy

    respond_to do |format|
      format.html { redirect_to sins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sins_helper.rb
module SinsHelper
end

app/views/sins/_form.html.erb
<%= form_for(@sin) do |f| %>
  <% if @sin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sin.errors.count, "error") %> prohibited this sin from being saved:</h2>

      <ul>
      <% @sin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.text_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sin_date %><br />
    <%= f.date_select :sin_date %>
  </div>
  <div class="field">
    <%= f.label :sin_time %><br />
    <%= f.time_select :sin_time %>
  </div>
  <div class="field">
    <%= f.label :sin_street_number %><br />
    <%= f.number_field :sin_street_number %>
  </div>
  <div class="field">
    <%= f.label :sin_street_name %><br />
    <%= f.text_field :sin_street_name %>
  </div>
  <div class="field">
    <%= f.label :sin_city %><br />
    <%= f.text_field :sin_city %>
  </div>
  <div class="field">
    <%= f.label :sin_state %><br />
    <%= f.text_field :sin_state %>
  </div>
  <div class="field">
    <%= f.label :sin_zipcode %><br />
    <%= f.number_field :sin_zipcode %>
  </div>
  <div class="field">
    <%= f.label :sin_country %><br />
    <%= f.text_field :sin_country %>
  </div>
  <div class="field">
    <%= f.label :sin %><br />
    <%= f.text_area :sin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sins/edit.html.erb
<h1>Editing sin</h1>

<%= render 'form' %>

<%= link_to 'Show', @sin %> |
<%= link_to 'Back', sins_path %>

app/views/sins/index.html.erb
<h1>Listing sins</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Title</th>
    <th>Sin date</th>
    <th>Sin time</th>
    <th>Sin street number</th>
    <th>Sin street name</th>
    <th>Sin city</th>
    <th>Sin state</th>
    <th>Sin zipcode</th>
    <th>Sin country</th>
    <th>Sin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sins.each do |sin| %>
  <tr>
    <td><%= sin.member_id %></td>
    <td><%= sin.title %></td>
    <td><%= sin.sin_date %></td>
    <td><%= sin.sin_time %></td>
    <td><%= sin.sin_street_number %></td>
    <td><%= sin.sin_street_name %></td>
    <td><%= sin.sin_city %></td>
    <td><%= sin.sin_state %></td>
    <td><%= sin.sin_zipcode %></td>
    <td><%= sin.sin_country %></td>
    <td><%= sin.sin %></td>
    <td><%= link_to 'Show', sin %></td>
    <td><%= link_to 'Edit', edit_sin_path(sin) %></td>
    <td><%= link_to 'Destroy', sin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sin', new_sin_path %>

app/views/sins/new.html.erb
<h1>New sin</h1>

<%= render 'form' %>

<%= link_to 'Back', sins_path %>

app/views/sins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @sin.member_id %>
</p>

<p>
  <b>Title:</b>
  <%= @sin.title %>
</p>

<p>
  <b>Sin date:</b>
  <%= @sin.sin_date %>
</p>

<p>
  <b>Sin time:</b>
  <%= @sin.sin_time %>
</p>

<p>
  <b>Sin street number:</b>
  <%= @sin.sin_street_number %>
</p>

<p>
  <b>Sin street name:</b>
  <%= @sin.sin_street_name %>
</p>

<p>
  <b>Sin city:</b>
  <%= @sin.sin_city %>
</p>

<p>
  <b>Sin state:</b>
  <%= @sin.sin_state %>
</p>

<p>
  <b>Sin zipcode:</b>
  <%= @sin.sin_zipcode %>
</p>

<p>
  <b>Sin country:</b>
  <%= @sin.sin_country %>
</p>

<p>
  <b>Sin:</b>
  <%= @sin.sin %>
</p>


<%= link_to 'Edit', edit_sin_path(@sin) %> |
<%= link_to 'Back', sins_path %>