config/routes.rb
Cc::Application.routes.draw do
  resources :repentances

  resources :charities

  resources :judgements

  resources :sins

  resources :members

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  attr_accessible :charity_type, :city, :country, :name, :phone_number, :state, :street_name, :street_number, :zipcode

  has_many :repentances

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charities }
    end
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
    @charity = Charity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charity }
    end
  end

  # GET /charities/new
  # GET /charities/new.json
  def new
    @charity = Charity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charity }
    end
  end

  # GET /charities/1/edit
  def edit
    @charity = Charity.find(params[:id])
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(params[:charity])

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render json: @charity, status: :created, location: @charity }
      else
        format.html { render action: "new" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charities/1
  # PUT /charities/1.json
  def update
    @charity = Charity.find(params[:id])

    respond_to do |format|
      if @charity.update_attributes(params[:charity])
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity = Charity.find(params[:id])
    @charity.destroy

    respond_to do |format|
      format.html { redirect_to charities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br />
    <%= f.number_field :street_number %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br />
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.number_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :charity_type %><br />
    <%= f.text_field :charity_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<h1>Listing charities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street number</th>
    <th>Street name</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>Phone number</th>
    <th>Charity type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charities.each do |charity| %>
  <tr>
    <td><%= charity.name %></td>
    <td><%= charity.street_number %></td>
    <td><%= charity.street_name %></td>
    <td><%= charity.city %></td>
    <td><%= charity.state %></td>
    <td><%= charity.zipcode %></td>
    <td><%= charity.country %></td>
    <td><%= charity.phone_number %></td>
    <td><%= charity.charity_type %></td>
    <td><%= link_to 'Show', charity %></td>
    <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
    <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Charity', new_charity_path %>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @charity.name %>
</p>

<p>
  <b>Street number:</b>
  <%= @charity.street_number %>
</p>

<p>
  <b>Street name:</b>
  <%= @charity.street_name %>
</p>

<p>
  <b>City:</b>
  <%= @charity.city %>
</p>

<p>
  <b>State:</b>
  <%= @charity.state %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @charity.zipcode %>
</p>

<p>
  <b>Country:</b>
  <%= @charity.country %>
</p>

<p>
  <b>Phone number:</b>
  <%= @charity.phone_number %>
</p>

<p>
  <b>Charity type:</b>
  <%= @charity.charity_type %>
</p>


<%= link_to 'Edit', edit_charity_path(@charity) %> |
<%= link_to 'Back', charities_path %>