config/routes.rb
Cc::Application.routes.draw do
  resources :repentances

  resources :charities

  resources :judgements

  resources :sins

  resources :members

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :age, :education_level, :email, :emloyment_status, :first_name, :last_name, :number_of_children, :partner, :password, :religon, :street_name, :street_number, :user_name, :zipcode

  has_many :sins
  has_many :judgements

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br />
    <%= f.number_field :street_number %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br />
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.number_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :religon %><br />
    <%= f.text_field :religon %>
  </div>
  <div class="field">
    <%= f.label :education_level %><br />
    <%= f.text_field :education_level %>
  </div>
  <div class="field">
    <%= f.label :partner %><br />
    <%= f.text_field :partner %>
  </div>
  <div class="field">
    <%= f.label :emloyment_status %><br />
    <%= f.text_field :emloyment_status %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :number_of_children %><br />
    <%= f.text_field :number_of_children %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>User name</th>
    <th>Password</th>
    <th>Street number</th>
    <th>Street name</th>
    <th>Zipcode</th>
    <th>Email</th>
    <th>Religon</th>
    <th>Education level</th>
    <th>Partner</th>
    <th>Emloyment status</th>
    <th>Age</th>
    <th>Number of children</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.first_name %></td>
    <td><%= member.last_name %></td>
    <td><%= member.user_name %></td>
    <td><%= member.password %></td>
    <td><%= member.street_number %></td>
    <td><%= member.street_name %></td>
    <td><%= member.zipcode %></td>
    <td><%= member.email %></td>
    <td><%= member.religon %></td>
    <td><%= member.education_level %></td>
    <td><%= member.partner %></td>
    <td><%= member.emloyment_status %></td>
    <td><%= member.age %></td>
    <td><%= member.number_of_children %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @member.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @member.last_name %>
</p>

<p>
  <b>User name:</b>
  <%= @member.user_name %>
</p>

<p>
  <b>Password:</b>
  <%= @member.password %>
</p>

<p>
  <b>Street number:</b>
  <%= @member.street_number %>
</p>

<p>
  <b>Street name:</b>
  <%= @member.street_name %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @member.zipcode %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Religon:</b>
  <%= @member.religon %>
</p>

<p>
  <b>Education level:</b>
  <%= @member.education_level %>
</p>

<p>
  <b>Partner:</b>
  <%= @member.partner %>
</p>

<p>
  <b>Emloyment status:</b>
  <%= @member.emloyment_status %>
</p>

<p>
  <b>Age:</b>
  <%= @member.age %>
</p>

<p>
  <b>Number of children:</b>
  <%= @member.number_of_children %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>